# Generated by Django 2.2.4 on 2022-10-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20221003_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.TextField(default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_planted', to='login_app.User')),
            ],
        ),
    ]
