# Generated by Django 2.2.4 on 2022-10-06 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
    ]
