# Generated by Django 2.2.4 on 2022-10-06 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('python_exam_app', '0002_auto_20221006_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 9, 28, 10, 726875, tzinfo=utc)),
        ),
    ]
