# Generated by Django 2.2.4 on 2022-10-06 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20221003_1521'),
        ('python_exam_app', '0003_auto_20221006_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='users_who_viwe',
            field=models.ManyToManyField(related_name='viewed_trees', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 6)),
        ),
    ]
